services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://n8n.aviatorstrainingcentre.in/
      - N8N_EDITOR_BASE_URL=https://n8n.aviatorstrainingcentre.in/
      - GENERIC_TIMEZONE=UTC
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
    volumes:
      - ../data:/home/node/.n8n
    env_file:
      - .env